# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.srcs/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/qdma_hbm_bd_qdma_0_0.xci
# IP: The module: 'qdma_hbm_bd_qdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] -quiet

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt} -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_ooc.xdc

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_ooc.xdc

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/qdma_hbm_bd_qdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/source/qdma_hbm_bd_qdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/synth/qdma_hbm_bd_qdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.srcs/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/qdma_hbm_bd_qdma_0_0.xci
# IP: The module: 'qdma_hbm_bd_qdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] -quiet

# IP: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt} -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_ooc.xdc

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/qdma_hbm_bd_qdma_0_0_pcie4c_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_impl_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_ooc.xdc

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/synth/qdma_hbm_bd_qdma_0_0_pcie4c_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/ip_pcie4c_uscale_plus_x1y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip || ORIG_REF_NAME==qdma_hbm_bd_qdma_0_0_pcie4c_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/qdma_hbm_bd_qdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/source/qdma_hbm_bd_qdma_0_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/CMAC-HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/synth/qdma_hbm_bd_qdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_qdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
