######################################################################
#
# File name : board_compile.do
# Created on: Thu Apr 03 10:09:48 CEST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/hbm_v1_0_16
vlib questa_lib/msim/xlconstant_v1_1_9
vlib questa_lib/msim/lib_cdc_v1_0_3
vlib questa_lib/msim/proc_sys_reset_v5_0_16
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_33
vlib questa_lib/msim/axi_vip_v1_1_19
vlib questa_lib/msim/gtwizard_ultrascale_v1_7_19
vlib questa_lib/msim/qdma_v5_0_12
vlib questa_lib/msim/blk_mem_gen_v8_4_9
vlib questa_lib/msim/axi_bram_ctrl_v4_1_11

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap hbm_v1_0_16 questa_lib/msim/hbm_v1_0_16
vmap xlconstant_v1_1_9 questa_lib/msim/xlconstant_v1_1_9
vmap lib_cdc_v1_0_3 questa_lib/msim/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_16 questa_lib/msim/proc_sys_reset_v5_0_16
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_33 questa_lib/msim/axi_register_slice_v2_1_33
vmap axi_vip_v1_1_19 questa_lib/msim/axi_vip_v1_1_19
vmap gtwizard_ultrascale_v1_7_19 questa_lib/msim/gtwizard_ultrascale_v1_7_19
vmap qdma_v5_0_12 questa_lib/msim/qdma_v5_0_12
vmap blk_mem_gen_v8_4_9 questa_lib/msim/blk_mem_gen_v8_4_9
vmap axi_bram_ctrl_v4_1_11 questa_lib/msim/axi_bram_ctrl_v4_1_11

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xilinx_vip  "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xpm  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"/work_extra/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl/hbm_v1_0_16.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work hbm_v1_0_16  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/hdl/hbm_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/verif/model/hbm_model.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/sim/qdma_hbm_bd_hbm_0_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xlconstant_v1_1_9  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_b98b_one_0.v" \

vcom -64 -93 -work lib_cdc_v1_0_3  \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -64 -93 -work proc_sys_reset_v5_0_16  \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_b98b_psr_aclk_0.vhd" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_b98b_arsw_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_b98b_rsw_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_b98b_awsw_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_b98b_wsw_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_b98b_bsw_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_b98b_s00mmu_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_b98b_s00tr_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_b98b_s00sic_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_b98b_s00a2s_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_b98b_sarn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_b98b_srn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_b98b_sawn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_b98b_swn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_b98b_sbn_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_b98b_m00s2a_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_b98b_m00arn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_b98b_m00rn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_b98b_m00awn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_b98b_m00wn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_b98b_m00bn_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_b98b_m00e_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_b98b_m01s2a_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_b98b_m01arn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_b98b_m01rn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_b98b_m01awn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_b98b_m01wn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_b98b_m01bn_0.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_b98b_m01e_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/bd_0/sim/bd_b98b.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work axi_infrastructure_v1_1_0  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work axi_register_slice_v2_1_33  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work axi_vip_v1_1_19  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/sim/qdma_hbm_bd_smartconnect_0_0.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0_clk_wiz.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_proc_sys_reset_0_0/sim/qdma_hbm_bd_proc_sys_reset_0_0.vhd" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work gtwizard_ultrascale_v1_7_19  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/53bc/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gtye4_channel_wrapper.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_common.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gtye4_common_wrapper.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gtwizard_gtye4.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gtwizard_top.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_cxs_remap.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_async_fifo.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_cc_intfc.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_cc_output_mux.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_cq_intfc.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_cq_output_mux.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_intfc_int.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_intfc.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_rc_intfc.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_rc_output_mux.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_rq_intfc.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_rq_output_mux.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_512b_sync_fifo.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_16k_int.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_16k.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_32k.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_4k_int.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_msix.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_rep_int.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_rep.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram_tph.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_bram.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gtwizard_top.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_phy_ff_chain.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_phy_pipeline.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gt_channel.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_gt_common.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_phy_clk.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_phy_rst.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_phy_rxeq.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_phy_txeq.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_sync_cell.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_sync.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_cdr_ctrl_on_eidle.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_receiver_detect_rxterm.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_gt_phy_wrapper.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_phy_top.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_init_ctrl.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_pl_eq.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_vf_decode.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_vf_decode_attr.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_pipe.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_seqnum_fifo.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_sys_clk_gen_ps.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source/qdma_hbm_bd_qdma_0_0_pcie4c_ip_pcie4c_uscale_core_top.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/sim/qdma_hbm_bd_qdma_0_0_pcie4c_ip.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work qdma_v5_0_12  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/qdma_v5_0_vl_rfs.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/qdma_hbm_bd_qdma_0_0hdl/verilog/qdma_hbm_bd_qdma_0_0_core_top.sv" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/sim/qdma_hbm_bd_qdma_0_0.sv" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work blk_mem_gen_v8_4_9  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_blk_mem_gen_0_0/sim/qdma_hbm_bd_blk_mem_gen_0_0.v" \

vcom -64 -93 -work axi_bram_ctrl_v4_1_11  \
"../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/df79/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_axi_bram_ctrl_0_0/sim/qdma_hbm_bd_axi_bram_ctrl_0_0.vhd" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/ip/qdma_hbm_bd_xlconstant_1_0/sim/qdma_hbm_bd_xlconstant_1_0.v" \
"../../../../pcie-hbm_sim.ip_user_files/bd/qdma_hbm_bd/sim/qdma_hbm_bd.v" \
"../../../../../../src/RP_model/pcie_4_c_rp.v" \
"../../../../../../src/RP_model/sys_clk_gen.v" \
"../../../../../../src/RP_model/sys_clk_gen_ds.v" \
"../../../../../../src/usrapp/usp_pci_exp_usrapp_cfg.v" \
"../../../../../../src/usrapp/usp_pci_exp_usrapp_com.v" \
"../../../../../../src/usrapp/usp_pci_exp_usrapp_rx.v" \
"../../../../../../src/RP_model/xilinx_pcie_uscale_rp.v" \
"../../../../../../src/RP_model/xp4c_usp_smsw_model_core_top.v" \

vlog -64 -incr -mfcu +notimingchecks -suppress 8602 -sv -L hbm_v1_0_16 -L qdma_v5_0_12 -L axi_vip_v1_1_19 -L smartconnect_v1_0 -L xilinx_vip -work xil_defaultlib  "+incdir+../../../../../../src/include" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/hdl/rtl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/7b8c/verif/model" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0127/hdl/verilog" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/ec67/hdl" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/3cbc" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_qdma_0_0/ip_0/source" "+incdir+../../../../pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ipshared/0e1b/hdl/verilog" "+incdir+/work_extra/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../../../src/qdma_top.sv" \
"../../../../../../src/usrapp/usp_pci_exp_usrapp_tx.sv" \
"../../../../../../src/qdma_tb.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

